%YAML:1.0

database:
    host:"127.0.0.1"
    user:"futtracker"
    pass:"futtracker"
    db:"futtracker"
    port:3306

model:
    captures:
        #- { type:file, view_type:1, path:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/0.avi", video_processor:{ type:bgs_selectivity,
            #learning_rate_background:3.0000000000000000e-02,learning_rate_foreground:2.5000000000000000e-02, threshold:30,
            #bg_model:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/0.png"}}
        #- { type:file, view_type:1, path:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/1.avi", video_processor:{ type:bgs_selectivity,
            #learning_rate_background:3.0000000000000000e-02,learning_rate_foreground:2.5000000000000000e-02, threshold:30,
            #bg_model:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/1.png"}}
        #- { type:file, view_type:0, path:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/4.avi", video_processor:{ type:bgs_selectivity,
            #learning_rate_background:3.0000000000000000e-02,learning_rate_foreground:2.5000000000000000e-02, threshold:30,
            #bg_model:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/4.png"}}
        - { type:file, view_type:1, path:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/0.avi",
            homography:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/Homography0D.xml",
            fps:10,close_iterations:2, min_area:150, max_area:2500,
            video_processor:{ type:bgs_gmm, history:200,
            threshold:40, learning_rate:.0500000000000000e-02,
            gaussian_kernel_size:{ w:3, h:3 },
            gaussian_stddev:1.2000000000000000e+00,
            bg_model:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/0.png"}}
        - { type:file, view_type:0, path:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/4.avi",
            homography:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/Homography4D.xml",
            fps:10, close_iterations:1, min_area:40, max_area:500,
            video_processor:{ type:bgs_gmm, history:200,
            threshold:20, learning_rate:.0500000000000000e-02,
            gaussian_kernel_size:{ w:3, h:3 },
            gaussian_stddev:0,
            bg_model:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/4.png"}}
        - { type:file, view_type:1, path:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/2.avi",
            homography:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/Homography2D.xml",
            fps:10, close_iterations:2, min_area:150, max_area:2500,
            video_processor:{ type:bgs_gmm, history:200,
            threshold:40, learning_rate:.0500000000000000e-02,
            gaussian_kernel_size:{ w:3, h:3 },
            gaussian_stddev:1.2000000000000000e+00,
            bg_model:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/2.png"}}
        #- { type:file, view_type:1, path:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/3.avi",
            #homography:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/Homography4D.xml",
            #fps:10, close_iterations:2, min_area:500, max_area:2500,
            #video_processor:{ type:bgs_gmm, history:200,
            #threshold:40, learning_rate:.0500000000000000e-02,
            #gaussian_kernel_size:{ w:3, h:3 },
            #gaussian_stddev:1.2000000000000000e+00,
            #bg_model:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/3.png"}}
        #- { type:file, view_type:1, path:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/0.avi", video_processor:{ type:bgs_selectivity,
            #learning_rate_background:3.0000000000000000e-02,learning_rate_foreground:2.5000000000000000e-02, threshold:30,
            #bg_model:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/0.png"}}
        #- { type:file, view_type:1, path:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/1.avi", video_processor:{ type:bgs_selectivity,
            #learning_rate_background:3.0000000000000000e-02,learning_rate_foreground:2.5000000000000000e-02, threshold:30,
            #bg_model:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/1.png"}}
        #- { type:file, view_type:0, path:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/4.avi", video_processor:{ type:bgs_selectivity,
            #learning_rate_background:3.0000000000000000e-02,learning_rate_foreground:2.5000000000000000e-02, threshold:30,
            #bg_model:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/4.png"}}
        #- { type:file, view_type:1, path:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/0.avi",
            #homography:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/Homography0D.xml",
            #dilate_iterations:1, erode_iterations:1, min_area:42,
            #video_processor:{ type:bgs_gmm, history:320,
            #threshold:50, learning_rate:4.5000000000000000e-03,
            #gaussian_kernel_size:{ w:3, h:3 },
            #gaussian_stddev:8.2000000000000000e+00,
            #bg_model:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/0.png"}}
        #- { type:file, view_type:1, path:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/2.avi",
            #homography:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/Homography2D.xml",
            #dilate_iterations:1, erode_iterations:1,
            #video_processor:{ type:bgs_gmm, history:320,
            #threshold:50, learning_rate:4.5000000000000000e-03,
            #gaussian_kernel_size:{ w:3, h:3 },
            #gaussian_stddev:1.2000000000000000e+00,
            #bg_model:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/2.png"}}
        #- { type:file, view_type:0, path:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/4.avi",
            #homography:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/Homography4D.xml",
            #dilate_iterations:1, erode_iterations:1, min_area:42,
            #video_processor:{ type:bgs_gmm, history:330,
            #threshold:50, learning_rate:1.5000000000000000e-03,
            #gaussian_kernel_size:{ w:3, h:3 },
            #gaussian_stddev:1.2000000000000000e+00,
            #bg_model:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/4.png"}}
    floor:{width:38, height:19}
    mixture_of_gaussians_detector:
        - {stddev:{x:1.8, y:1.8}, limit_distance:{x:3, y:3}}
        - {stddev:{x:1.8, y:1.8}, limit_distance:{x:3, y:3}}
        - {stddev:{x:1.8, y:1.8}, limit_distance:{x:3, y:3}}
        #- {stddev:{x:1.3, y:1.3}, limit_distance:{x:3, y:3}}


