%YAML:1.0

database:
    host:"127.0.0.1"
    user:"futtracker"
    pass:"futtracker"
    db:"futtracker"
    port:3306
    
captures:
   - { type:file, path:"C:/Users/Matheus/Datasets/Dataset/21-01/Sync/Treino1/0.avi", video_processor:{ type:bgs, history:50,
       threshold:100, learning_rate:2.0000000000000000e-03,
       gaussian_kernel_size:{ w:3, h:3 },
       gaussian_stddev:1.2000000000000000e+00},
       bg_model:"C:/Users/Matheus/Datasets/Dataset/21-01/Sync/Treino1/bg.png"}
   #- { type:file, path:"C:/Users/Matheus/Datasets/Dataset/21-01/Sync/Treino1/1.avi", video_processor:{ type:bgs, history:100,
       #threshold:40, learning_rate:2.0000000000000000e-03,
       #gaussian_kernel_size:{ w:3, h:3 },
       #gaussian_stddev:1.2000000000000000e+00 } }
   #- { type:file, path:"C:/Users/Matheus/Datasets/Dataset/21-01/Sync/Treino1/2.avi", video_processor:{ type:bgs, history:100,
       #threshold:40, learning_rate:2.0000000000000000e-03,
       #gaussian_kernel_size:{ w:3, h:3 },
       #gaussian_stddev:1.2000000000000000e+00 } }
   #- { type:file, path:"C:/Users/Matheus/Datasets/Dataset/21-01/Sync/Treino1/3.avi", video_processor:{ type:bgs, history:100,
       #threshold:40, learning_rate:2.0000000000000000e-03,
       #gaussian_kernel_size:{ w:3, h:3 },
       #gaussian_stddev:1.2000000000000000e+00 } }

