%YAML:1.0

database:
    host:"127.0.0.1"
    user:"futtracker"
    pass:"futtracker"
    db:"futtracker"
    port:3306

model:
    captures:
        #- { type:file, view_type:1, path:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/0.avi", video_processor:{ type:bgs_selectivity,
            #learning_rate_background:3.0000000000000000e-02,learning_rate_foreground:2.5000000000000000e-02, threshold:30,
            #bg_model:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/0.png"}}
        #- { type:file, view_type:1, path:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/1.avi", video_processor:{ type:bgs_selectivity,
            #learning_rate_background:3.0000000000000000e-02,learning_rate_foreground:2.5000000000000000e-02, threshold:30,
            #bg_model:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/1.png"}}
        #- { type:file, view_type:0, path:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/4.avi", video_processor:{ type:bgs_selectivity,
            #learning_rate_background:3.0000000000000000e-02,learning_rate_foreground:2.5000000000000000e-02, threshold:30,
            #bg_model:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/4.png"}}
        #- { type:file, view_type:1, path:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/0.avi",
            #dilate_iterations:1, erode_iterations:1,
            #video_processor:{ type:bgs_gmm, history:50,
            #threshold:40, learning_rate:.5000000000000000e-03,
            #gaussian_kernel_size:{ w:3, h:3 },
            #gaussian_stddev:1.2000000000000000e+00,
            #bg_model:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/0.png"}}
        #- { type:file, view_type:1, path:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/2.avi",
            #dilate_iterations:1, erode_iterations:1,
            #video_processor:{ type:bgs_gmm, history:50,
            #threshold:40, learning_rate:.5000000000000000e-03,
            #gaussian_kernel_size:{ w:3, h:3 },
            #gaussian_stddev:1.2000000000000000e+00,
            #bg_model:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/2.png"}}
        #- { type:file, view_type:0, path:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/4.avi",
            #dilate_iterations:1, erode_iterations:1,
            #video_processor:{ type:bgs_gmm, history:50,
            #threshold:40, learning_rate:.5000000000000000e-03,
            #gaussian_kernel_size:{ w:3, h:3 },
            #gaussian_stddev:1.2000000000000000e+00,
            #bg_model:"/home/matheus/Datasets/Futtracker/21-01/Sync/Treino1/4.png"}}
        #- { type:file, view_type:1, path:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/0.avi", video_processor:{ type:bgs_selectivity,
            #learning_rate_background:3.0000000000000000e-02,learning_rate_foreground:2.5000000000000000e-02, threshold:30,
            #bg_model:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/0.png"}}
        #- { type:file, view_type:1, path:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/1.avi", video_processor:{ type:bgs_selectivity,
            #learning_rate_background:3.0000000000000000e-02,learning_rate_foreground:2.5000000000000000e-02, threshold:30,
            #bg_model:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/1.png"}}
        #- { type:file, view_type:0, path:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/4.avi", video_processor:{ type:bgs_selectivity,
            #learning_rate_background:3.0000000000000000e-02,learning_rate_foreground:2.5000000000000000e-02, threshold:30,
            #bg_model:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/4.png"}}
        - { type:file, view_type:1, path:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/0.avi",
            dilate_iterations:1, erode_iterations:1,
            video_processor:{ type:bgs_gmm, history:50,
            threshold:40, learning_rate:.5000000000000000e-03,
            gaussian_kernel_size:{ w:3, h:3 },
            gaussian_stddev:1.2000000000000000e+00,
            bg_model:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/0.png"}}
        - { type:file, view_type:1, path:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/2.avi",
            dilate_iterations:1, erode_iterations:1,
            video_processor:{ type:bgs_gmm, history:50,
            threshold:40, learning_rate:.5000000000000000e-03,
            gaussian_kernel_size:{ w:3, h:3 },
            gaussian_stddev:1.2000000000000000e+00,
            bg_model:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/2.png"}}
        - { type:file, view_type:0, path:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/4.avi",
            dilate_iterations:1, erode_iterations:1,
            video_processor:{ type:bgs_gmm, history:50,
            threshold:40, learning_rate:.5000000000000000e-03,
            gaussian_kernel_size:{ w:3, h:3 },
            gaussian_stddev:1.2000000000000000e+00,
            bg_model:"C:/Users/Matheus/Datasets/Futtracker/21-01/Sync/Treino1/4.png"}}
    tracker:{ occupation_map:{ floor:{w:100, h:100} } }


